spring:
  datasource:
    url: jdbc:mysql://139.196.194.172:3306/electric_bicycle_pro_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    userName: jjtest
    password: 99b39189a35c
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10
#  data:
#    elasticsearch:
##      cluster-name: elasticsearch
#      cluster-nodes: 172.16.20.14:9300
#      repositories:
#        enabled: true
  redis:
    database: 4
    host: 139.196.194.172
    password: test123
    port: 6379
    pool:
      max-active: 8
      max-wait: 1000
    timeout: 1000

# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis/mybatis.xml


sms.prefix: applet
sms.url: http://106.15.47.133:8080/sms/captcha
sms.checkUrl: http://106.15.47.133:8080/sms/ckCaptcha

wxAppletRootUrl: http://139.196.250.4/payback/wxPayBack/callBack