spring:
  datasource:
    url: jdbc:mysql://139.196.194.172:3306/electric_bicycle_pro_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    userName: jjtest
    password: 99b39189a35c
    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    elasticsearch:
##      cluster-name: elasticsearch
#      cluster-nodes: 172.16.20.14:9300
#      repositories:
#        enabled: true
#  redis:
#    database: 10
#    host: 172.16.20.235
#    password: test123
#    port: 6379
#    pool:
#      max-active: 8
#      max-idle: 1000
#      min-idle: 0
#      max-wait: -1

# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis/mybatis.xml


wcx.serviceUrl: https://test.wcx.qq.com/fcgi-bin/