spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    userName: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
#      cluster-name: elasticsearch
      cluster-nodes: 172.16.20.14:9300
      repositories:
        enabled: true
#      properties:
#        logs: ./elasticsearch/log #elasticsearch日志存储目录
#        data: ./elasticsearch/data #elasticsearch数据存储目录

# LOGGING
logging:
    level:
       com.example: DEBUG
    config: classpath:logback/logback-dev.xml
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis/mybatis.xml