server:
  port: 3333
#  ssl.key-store: classpath:214075900090332.pfx
#  ssl.key-store-password: 214075900090332
#  ssl.keyStoreType: PKCS12

spring:
  freemarker:
    prefer-file-system-access: false
  application:
       name: jjwxapplet
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  profiles:
    active: dev
#    active: prod
  http:
    encoding:
      charset: utf-8
      enabled: true #是否开启http的编码支持
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  aop:
      proxy-target-class: true
  jmx:
    default-domain: applet

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.appletper


wxApplet.appId: wxd1cfbb46ce504c75
wxApplet.appSecret: b9ed8ecf76a6156455d9d0b6bcf46330
wxApplet.sessionTime: 1800


api.sign: 402880496058fbb7016058fc201e0009