server:
  port: 8080

server.ssl.key-store: classpath:214075900090332.pfx
server.ssl.key-store-password: 214075900090332
server.ssl.keyStoreType: PKCS12

spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true #是否开启http的编码支持
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
  aop:
        proxy-target-class: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.weichuxing.mapper

logging:
    level:
    config: classpath:logback/logback-dev.xml

wxApplet.appId: wxd1cfbb46ce504c75
wxApplet.appSecret: 0299e03792b42b1bc589d1ed7aeec50a
wxApplet.sessionTime: 1800

